void iniciacao()
{
  // LIGA
  digitalWrite(L1, HIGH);
  delay(90);
  digitalWrite(L2, HIGH);
  delay(90);
  digitalWrite(L3, HIGH);
  delay(90);
  digitalWrite(L4, HIGH);
  delay(90);
  digitalWrite(L5, HIGH);
  delay(90);
  digitalWrite(L6, HIGH);
  delay(90);
  digitalWrite(L7, HIGH);
  delay(90);
  digitalWrite(L8, HIGH);
  delay(90);
  digitalWrite(L9, HIGH);
  delay(90);
  digitalWrite(L10, HIGH);
  delay(90);
  digitalWrite(L11, HIGH);
  delay(90);
  digitalWrite(L12, HIGH);
  delay(90);
  digitalWrite(L13, HIGH);
  delay(90);
  digitalWrite(L14, HIGH);
  delay(90);
  digitalWrite(L15, HIGH);
  delay(90);
  digitalWrite(L16, HIGH);
  delay(2000);
  //DESLIGA
  digitalWrite(L1, LOW);
  delay(90);
  digitalWrite(L2, LOW);
  delay(90);
  digitalWrite(L3, LOW);
  delay(90);
  digitalWrite(L4, LOW);
  delay(90);
  digitalWrite(L5, LOW);
  delay(90);
  digitalWrite(L6, LOW);
  delay(90);
  digitalWrite(L7, LOW);
  delay(90);
  digitalWrite(L8, LOW);
  delay(90);
  digitalWrite(L9, LOW);
  delay(90);
  digitalWrite(L10, LOW);
  delay(90);
  digitalWrite(L11, LOW);
  delay(90);
  digitalWrite(L12, LOW);
  delay(90);
  digitalWrite(L13, LOW);
  delay(90);
  digitalWrite(L14, LOW);
  delay(90);
  digitalWrite(L15, LOW);
  delay(90);
  digitalWrite(L16, LOW);
  delay(90);
}
